version: '3'

services:
  backend: &backend
    container_name: backend
    build:
      context: ./backend
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env
    depends_on:
      - celery
      - rabbitmq

  celery: &celery
    <<: *backend
    container_name: celery
    build:
      context: ./backend
      dockerfile: celery.Dockerfile
    ports: [ ]
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  rabbitmq_data:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs